import 'package:google_maps_flutter/google_maps_flutter.dart';

import 'package:dinosaur/page/home/point.dart';

/// 一組輕量的假資料，方便在沒有後端時測試徽章與地圖呈現。
const List<Point> mockPoints = <Point>[
  Point(
    id: 'mock-point-001',
    name: '台北車站',
    location: LatLng(25.0478, 121.5170),
    area: '中正區',
    description: '城市跑點 #1',
    isNFCEnabled: true,
    collected: true,
  ),
  Point(
    id: 'mock-point-002',
    name: '總統府',
    location: LatLng(25.0401, 121.5111),
    area: '中正區',
    description: '城市跑點 #2',
    isNFCEnabled: true,
    collected: true,
  ),
  Point(
    id: 'mock-point-003',
    name: '西門町',
    location: LatLng(25.0421, 121.5078),
    area: '萬華區',
    description: '城市跑點 #3',
    isNFCEnabled: false,
    collected: false,
  ),
  Point(
    id: 'mock-point-004',
    name: '龍山寺',
    location: LatLng(25.0375, 121.4997),
    area: '萬華區',
    description: '城市跑點 #4',
    isNFCEnabled: false,
    collected: false,
  ),
  Point(
    id: 'mock-point-005',
    name: '大稻埕碼頭',
    location: LatLng(25.0556, 121.5108),
    area: '大同區',
    description: '城市跑點 #5',
    isNFCEnabled: true,
    collected: false,
  ),
  Point(
    id: 'mock-point-006',
    name: '象山步道',
    location: LatLng(25.0270, 121.5753),
    area: '信義區',
    description: '城市跑點 #6',
    isNFCEnabled: true,
    collected: true,
  ),
  Point(
    id: 'mock-point-007',
    name: '台北101',
    location: LatLng(25.0339, 121.5645),
    area: '信義區',
    description: '城市跑點 #7',
    isNFCEnabled: true,
    collected: true,
  ),
  Point(
    id: 'mock-point-008',
    name: '松菸文創園區',
    location: LatLng(25.0441, 121.5610),
    area: '信義區',
    description: '城市跑點 #8',
    isNFCEnabled: false,
    collected: false,
  ),
  Point(
    id: 'mock-point-009',
    name: '大安森林公園',
    location: LatLng(25.0330, 121.5334),
    area: '大安區',
    description: '城市跑點 #9',
    isNFCEnabled: true,
    collected: true,
  ),
  Point(
    id: 'mock-point-010',
    name: '國立台灣大學',
    location: LatLng(25.0173, 121.5390),
    area: '大安區',
    description: '城市跑點 #10',
    isNFCEnabled: false,
    collected: false,
  ),
  Point(
    id: 'mock-point-011',
    name: '師大夜市',
    location: LatLng(25.0260, 121.5270),
    area: '大安區',
    description: '城市跑點 #11',
    isNFCEnabled: false,
    collected: false,
  ),
  Point(
    id: 'mock-point-012',
    name: '士林夜市',
    location: LatLng(25.0883, 121.5250),
    area: '士林區',
    description: '城市跑點 #12',
    isNFCEnabled: true,
    collected: true,
  ),
  Point(
    id: 'mock-point-013',
    name: '故宮博物院',
    location: LatLng(25.1024, 121.5485),
    area: '士林區',
    description: '城市跑點 #13',
    isNFCEnabled: true,
    collected: false,
  ),
];

